"use client";

import { useState } from "react";
import { GraduationCap, Trophy, Check, HelpCircle, ArrowRight } from "lucide-react";

const PHISHING_TIPS = [
  {
    id: 1,
    title: "Double Check the Domain Spelling",
    desc: "Look closely at the domain name. Phishers use domain typos (typosquatting) like 'g00gle.com' instead of 'google.com' or 'paypal-security.com' instead of 'paypal.com'.",
  },
  {
    id: 2,
    title: "Look for Insecure Connections",
    desc: "Ensure the URL starts with 'https://' rather than 'http://'. While HTTPS doesn't guarantee safety, HTTP is completely unencrypted and highly suspicious for financial websites.",
  },
  {
    id: 3,
    title: "Stacking Subdomains Obfuscation",
    desc: "Phishing links often stack subdomains to trick you, e.g. 'paypal.com.secure.login-update.com'. The real domain is the last part before the TLD ('login-update.com').",
  },
  {
    id: 4,
    title: "Beware of Shortened Links",
    desc: "Link shorteners (like bit.ly, tinyurl) mask the final destination URL. Always scan shortened URLs or inspect them before logging into accounts.",
  },
  {
    id: 5,
    title: "Avoid Random-Looking Hostnames",
    desc: "Legitimate businesses rarely use highly random domain names (e.g. 'hs72hd9w.com'). These are usually auto-generated by attackers to bypass domain-blacklist filters.",
  },
];

const QUIZ_QUESTIONS = [
  {
    question: "Which of the following URLs is the REAL Paypal website?",
    options: [
      "https://paypal.com.secure-login.us",
      "https://www.paypal.com",
      "http://www-paypal-login.com",
      "https://paypa1.com",
    ],
    correct: 1,
    feedback:
      "Correct! Only 'paypal.com' is the official domain. The others use subdomains, typosquatting (paypa1), or insecure protocols.",
  },
  {
    question: "A link uses a URL shortener like 'bit.ly/3gHj9'. What should you do?",
    options: [
      "Trust it because it looks clean and short.",
      "Click it immediately to see where it goes.",
      "Scan it with a verification app (like Secure OS) before entering credentials.",
      "Assume all shortened links are virus-free.",
    ],
    correct: 2,
    feedback:
      "Correct! URL shorteners hide the real destination, making them common tools for phishers. Scanning first keeps you safe.",
  },
  {
    question: "What does the Shannon Entropy check measure in a domain name?",
    options: [
      "The speed of the network connection.",
      "The randomness of characters in the domain (e.g. tracking generated spam domains).",
      "Whether the site uses cookies.",
      "The server geographical location.",
    ],
    correct: 1,
    feedback:
      "Correct! Higher entropy indicates a more random and auto-generated domain string, which is a major signal of disposable phishing sites.",
  },
];

export default function SecurityGuideTab() {
  const [quizIndex, setQuizIndex] = useState(0);
  const [quizAnswer, setQuizAnswer] = useState(null);
  const [quizCorrectCount, setQuizCorrectCount] = useState(0);

  const handleQuizAnswer = (index) => {
    setQuizAnswer(index);
    if (index === QUIZ_QUESTIONS[quizIndex].correct) {
      setQuizCorrectCount((c) => c + 1);
    }
  };

  const handleNextQuiz = () => {
    setQuizAnswer(null);
    setQuizIndex((prev) => (prev + 1) % QUIZ_QUESTIONS.length);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
      
      {/* Tips Left Column */}
      <div className="lg:col-span-7 space-y-6">
        <h2 className="text-lg font-bold text-navy flex items-center gap-2 px-1">
          <GraduationCap className="h-5 w-5 text-primary" /> Phishing Detection Guide
        </h2>
        
        <div className="space-y-4">
          {PHISHING_TIPS.map((tip) => (
            <div key={tip.id} className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-3">
              <div className="flex items-center gap-2.5">
                <span className="h-5 w-5 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-bold text-[10px]">
                  {tip.id}
                </span>
                <h3 className="font-heading font-bold text-xs text-navy leading-none">{tip.title}</h3>
              </div>
              <p className="text-xs text-text-secondary leading-relaxed">
                {tip.desc}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Quiz Right Column */}
      <div className="lg:col-span-5">
        <div className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-sm space-y-6">
          
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <span className="bg-primary/10 text-primary text-[10px] uppercase font-bold px-2.5 py-0.5 rounded-lg border border-primary/20 flex items-center gap-1.5">
              <Trophy className="h-3.5 w-3.5" /> Test Your Skill
            </span>
            <span className="text-[10px] text-text-secondary font-bold flex items-center gap-1">
              <Check className="h-3.5 w-3.5 text-green-500" /> {quizCorrectCount}/{QUIZ_QUESTIONS.length} Correct
            </span>
          </div>

          <div className="space-y-4">
            <span className="text-[10px] text-text-muted font-bold block uppercase tracking-wider">
              Question {quizIndex + 1} of {QUIZ_QUESTIONS.length}
            </span>
            <h3 className="font-heading font-bold text-sm text-navy leading-relaxed">
              {QUIZ_QUESTIONS[quizIndex].question}
            </h3>
          </div>

          <div className="space-y-2 pt-2">
            {QUIZ_QUESTIONS[quizIndex].options.map((option, idx) => {
              let styleClass = "border-slate-200 hover:bg-slate-50 text-text-secondary";
              if (quizAnswer !== null) {
                if (idx === QUIZ_QUESTIONS[quizIndex].correct) {
                  styleClass = "bg-green-50 border-green-200 text-green-700 font-bold";
                } else if (idx === quizAnswer) {
                  styleClass = "bg-red-50 border-red-200 text-red-700 font-bold";
                } else {
                  styleClass = "border-slate-100 text-text-muted opacity-60";
                }
              }

              return (
                <button
                  key={idx}
                  onClick={() => quizAnswer === null && handleQuizAnswer(idx)}
                  disabled={quizAnswer !== null}
                  className={`w-full text-left rounded-xl border p-3.5 text-xs font-medium transition-all ${styleClass}`}
                >
                  <span className="mr-2 font-bold text-navy opacity-60">
                    {String.fromCharCode(65 + idx)}.
                  </span>
                  {option}
                </button>
              );
            })}
          </div>

          {quizAnswer !== null && (
            <div className={`p-4 rounded-xl border animate-in fade-in duration-200 space-y-4 ${
              quizAnswer === QUIZ_QUESTIONS[quizIndex].correct 
                ? "bg-green-50 border-green-200 text-green-800" 
                : "bg-red-50 border-red-200 text-red-800"
            }`}>
              <div className="text-xs flex gap-2 items-start leading-relaxed">
                <HelpCircle className="h-4.5 w-4.5 shrink-0 mt-0.5" />
                <span>
                  {quizAnswer === QUIZ_QUESTIONS[quizIndex].correct ? "Correct Choice! " : "Incorrect Selection. "}
                  {QUIZ_QUESTIONS[quizIndex].feedback}
                </span>
              </div>
              
              <button
                onClick={handleNextQuiz}
                className="w-full inline-flex h-9 items-center justify-center gap-1.5 rounded-lg bg-navy hover:bg-navy-dark text-white text-xs font-semibold shadow-sm transition-colors"
              >
                Next Question <ArrowRight className="h-3.5 w-3.5" />
              </button>
            </div>
          )}
        </div>
      </div>

    </div>
  );
}
