"use client";

import { useState } from "react";

const PHISHING_TIPS = [
  {
    id: 1,
    title: "Double Check the Domain",
    desc: "Look closely at the domain name. Phishers use domain typos (typosquatting) like 'g00gle.com' instead of 'google.com' or 'paypal-security.com' instead of 'paypal.com'.",
  },
  {
    id: 2,
    title: "Look for Insecure Connections",
    desc: "Ensure the URL starts with 'https://' rather than 'http://'. While HTTPS doesn't guarantee safety, HTTP is completely unencrypted and highly suspicious for financial websites.",
  },
  {
    id: 3,
    title: "Too Many Subdomains",
    desc: "Phishing links often stack subdomains to trick you, e.g. 'paypal.com.secure.login-update.com'. The real domain is the last part before the TLD ('login-update.com').",
  },
  {
    id: 4,
    title: "Beware of Shortened Links",
    desc: "Link shorteners (like bit.ly, tinyurl) mask the final destination URL. Always scan shortened URLs or inspect them before logging into accounts.",
  },
  {
    id: 5,
    title: "Avoid Random-Looking URLs",
    desc: "Legitimate businesses rarely use highly random domain names (e.g. 'hs72hd9w.com'). These are usually auto-generated by attackers to bypass domain-blacklist filters.",
  },
];

const QUIZ_QUESTIONS = [
  {
    question: "Which of the following URLs is the REAL Paypal website?",
    options: [
      "https://paypal.com.secure-login.us",
      "https://www.paypal.com",
      "http://www-paypal-login.com",
      "https://paypa1.com",
    ],
    correct: 1,
    feedback:
      "Correct! Only 'paypal.com' is the official domain. The others use subdomains, typosquatting (paypa1), or insecure protocols.",
  },
  {
    question: "A link uses a URL shortener like 'bit.ly/3gHj9'. What should you do?",
    options: [
      "Trust it because it looks clean and short.",
      "Click it immediately to see where it goes.",
      "Scan it with a verification app (like Secure OS) before entering credentials.",
      "Assume all shortened links are virus-free.",
    ],
    correct: 2,
    feedback:
      "Correct! URL shorteners hide the real destination, making them common tools for phishers. Scanning first keeps you safe.",
  },
  {
    question: "What does the Shannon Entropy check measure in a domain name?",
    options: [
      "The speed of the network connection.",
      "The randomness of characters in the domain (e.g. tracking generated spam domains).",
      "Whether the site uses cookies.",
      "The server geographical location.",
    ],
    correct: 1,
    feedback:
      "Correct! Higher entropy indicates a more random and auto-generated domain string, which is a major signal of disposable phishing sites.",
  },
];

export default function SecurityGuideTab() {
  const [quizIndex, setQuizIndex] = useState(0);
  const [quizAnswer, setQuizAnswer] = useState(null);
  const [quizCorrectCount, setQuizCorrectCount] = useState(0);

  const handleQuizAnswer = (index) => {
    setQuizAnswer(index);
    if (index === QUIZ_QUESTIONS[quizIndex].correct) {
      setQuizCorrectCount((c) => c + 1);
    }
  };

  const handleNextQuiz = () => {
    setQuizAnswer(null);
    setQuizIndex((prev) => (prev + 1) % QUIZ_QUESTIONS.length);
  };

  return (
    <div className="dual-panel">
      {/* Tips Left */}
      <div className="panel-left">
        <h2 style={{ fontSize: "24px", fontWeight: "800", marginBottom: "20px", paddingLeft: "4px" }}>
          🎓 Security Guide
        </h2>
        {PHISHING_TIPS.map((tip) => (
          <div key={tip.id} className="tip-card glass-card">
            <div className="tip-header">
              <span className="tip-num">{tip.id}</span>
              <h3 className="tip-title">{tip.title}</h3>
            </div>
            <p style={{ fontSize: "14px", color: "var(--text-secondary)", lineHeight: "1.5" }}>
              {tip.desc}
            </p>
          </div>
        ))}
      </div>

      {/* Quiz Right */}
      <div className="panel-right">
        <div className="quiz-card glass-card">
          <div style={{ display: "flex", alignItems: "center", justifyItems: "center", justifyContent: "space-between" }}>
            <span className="quiz-tag">🎮 Test Your Skill</span>
            <span style={{ fontSize: "12px", color: "var(--text-muted)", fontWeight: "700" }}>
              ✅ {quizCorrectCount}/{QUIZ_QUESTIONS.length} Correct
            </span>
          </div>

          <p className="quiz-progress-text">
            Question {quizIndex + 1} of {QUIZ_QUESTIONS.length}
          </p>

          <h3 className="quiz-question">{QUIZ_QUESTIONS[quizIndex].question}</h3>

          <div className="quiz-options">
            {QUIZ_QUESTIONS[quizIndex].options.map((option, idx) => {
              let btnClass = "";
              if (quizAnswer !== null) {
                if (idx === QUIZ_QUESTIONS[quizIndex].correct) {
                  btnClass = "correct";
                } else if (idx === quizAnswer) {
                  btnClass = "incorrect";
                }
              }

              return (
                <button
                  key={idx}
                  onClick={() => quizAnswer === null && handleQuizAnswer(idx)}
                  className={`quiz-option ${btnClass}`}
                  disabled={quizAnswer !== null}
                >
                  <span style={{ marginRight: "8px", fontWeight: "800", opacity: 0.6 }}>
                    {String.fromCharCode(65 + idx)}.
                  </span>
                  {option}
                </button>
              );
            })}
          </div>

          {quizAnswer !== null && (
            <div
              className={`quiz-feedback ${
                quizAnswer === QUIZ_QUESTIONS[quizIndex].correct ? "success" : "error"
              }`}
            >
              <p>
                {quizAnswer === QUIZ_QUESTIONS[quizIndex].correct ? "🎉 " : "❌ "}
                {QUIZ_QUESTIONS[quizIndex].feedback}
              </p>
              <button
                onClick={handleNextQuiz}
                className="btn btn-secondary mt-2"
                style={{ padding: "10px 18px", fontSize: "13px", borderRadius: "12px" }}
              >
                Next Question →
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
