"use client";

import { useState, useEffect } from "react";
import { analyzeURL } from "../lib/phishingEngine";
import dynamic from "next/dynamic";
const QrScanner = dynamic(() => import("./components/QrScanner"), { ssr: false });

export default function Home() {
  const [activeTab, setActiveTab] = useState("check"); // 'check' | 'qr' | 'history' | 'tips'
  const [urlInput, setUrlInput] = useState("");
  const [isOnline, setIsOnline] = useState(true);
  const [scanResult, setScanResult] = useState(null);
  const [scanHistory, setScanHistory] = useState([]);
  
  // Quiz State
  const [quizAnswer, setQuizAnswer] = useState(null);
  const [quizIndex, setQuizIndex] = useState(0);

  // Default tips list
  const phishingTips = [
    {
      id: 1,
      title: "Double Check the Domain",
      desc: "Look closely at the domain name. Phishers use domain typos (typosquatting) like 'g00gle.com' instead of 'google.com' or 'paypal-security.com' instead of 'paypal.com'."
    },
    {
      id: 2,
      title: "Look for Insecure Connections",
      desc: "Ensure the URL starts with 'https://' rather than 'http://'. While HTTPS doesn't guarantee safety, HTTP is completely unencrypted and highly suspicious for financial websites."
    },
    {
      id: 3,
      title: "Too Many Subdomains",
      desc: "Phishing links often stack subdomains to trick you, e.g. 'paypal.com.secure.login-update.com'. The real domain is the last part before the TLD ('login-update.com')."
    },
    {
      id: 4,
      title: "Beware of Shortened Links",
      desc: "Link shorteners (like bit.ly, tinyurl) mask the final destination URL. Always scan shortened URLs or inspect them before logging into accounts."
    },
    {
      id: 5,
      title: "Avoid Random-Looking URLs",
      desc: "Legitimate businesses rarely use highly random domain names (e.g. 'hs72hd9w.com'). These are usually auto-generated by attackers to bypass domain-blacklist filters."
    }
  ];

  // Phishing safety quiz questions
  const quizQuestions = [
    {
      question: "Which of the following URLs is the REAL Paypal website?",
      options: [
        "https://paypal.com.secure-login.us",
        "https://www.paypal.com",
        "http://www-paypal-login.com",
        "https://paypa1.com"
      ],
      correct: 1,
      feedback: "Correct! Only 'paypal.com' is the official domain. The others use subdomains, typosquatting (paypa1), or insecure protocols."
    },
    {
      question: "A link uses a URL shortener like 'bit.ly/3gHj9'. What should you do?",
      options: [
        "Trust it because it looks clean and short.",
        "Click it immediately to see where it goes.",
        "Scan it with a verification app (like PhishGuard) before entering credentials.",
        "Assume all shortened links are virus-free."
      ],
      correct: 2,
      feedback: "Correct! URL shorteners hide the real destination, making them common tools for phishers. Scanning first keeps you safe."
    },
    {
      question: "What does the Shannon Entropy check measure in a domain name?",
      options: [
        "The speed of the network connection.",
        "The randomness of characters in the domain (e.g. tracking generated spam domains).",
        "Whether the site uses cookies.",
        "The server geographical location."
      ],
      correct: 1,
      feedback: "Correct! Higher entropy indicates a more random and auto-generated domain string, which is a major signal of disposable phishing sites."
    }
  ];

  // Check online/offline status
  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsOnline(navigator.onLine);
      const handleOnline = () => setIsOnline(true);
      const handleOffline = () => setIsOnline(false);

      window.addEventListener("online", handleOnline);
      window.addEventListener("offline", handleOffline);

      // Load History from Local Storage
      const savedHistory = localStorage.getItem("phishguard_history");
      if (savedHistory) {
        setScanHistory(JSON.parse(savedHistory));
      } else {
        // Mock data to start
        const mockHistory = [
          {
            url: "https://www.google.com",
            rating: "SAFE",
            score: 100,
            date: new Date(Date.now() - 3600000 * 2).toLocaleDateString()
          },
          {
            url: "http://secure-paypal-login.com/update",
            rating: "DANGEROUS",
            score: 15,
            date: new Date(Date.now() - 3600000 * 24).toLocaleDateString()
          }
        ];
        setScanHistory(mockHistory);
        localStorage.setItem("phishguard_history", JSON.stringify(mockHistory));
      }

      return () => {
        window.removeEventListener("online", handleOnline);
        window.removeEventListener("offline", handleOffline);
      };
    }
  }, []);

  // Run Link Analysis
  const handleCheckUrl = (urlToCheck) => {
    const targetUrl = urlToCheck || urlInput;
    if (!targetUrl.trim()) return;

    const result = analyzeURL(targetUrl);
    setScanResult(result);

    // Save to History (no duplicates in recent list)
    const newHistoryItem = {
      url: result.url,
      rating: result.rating,
      score: result.score,
      date: new Date().toLocaleDateString()
    };

    setScanHistory(prevHistory => {
      const filtered = prevHistory.filter(item => item.url.toLowerCase() !== result.url.toLowerCase());
      const updated = [newHistoryItem, ...filtered].slice(0, 15); // limit to 15 items
      localStorage.setItem("phishguard_history", JSON.stringify(updated));
      return updated;
    });

    if (!urlToCheck) {
      // Input was typed, scroll or update view if needed
    }
  };

  // QR Code Scanner Success Handler
  const handleQrScanSuccess = (decodedUrl) => {
    setUrlInput(decodedUrl);
    setActiveTab("check");
    handleCheckUrl(decodedUrl);
  };

  // Clear Input
  const handleClearInput = () => {
    setUrlInput("");
    setScanResult(null);
  };

  // Clear Scan History
  const handleClearHistory = () => {
    setScanHistory([]);
    localStorage.removeItem("phishguard_history");
  };

  // Quiz Option Click
  const handleQuizAnswer = (index) => {
    setQuizAnswer(index);
  };

  // Next Quiz Question
  const handleNextQuiz = () => {
    setQuizAnswer(null);
    setQuizIndex((prev) => (prev + 1) % quizQuestions.length);
  };

  // Get color scale for rating
  const getRatingColorClass = (rating) => {
    if (rating === "SAFE") return "safe";
    if (rating === "SUSPICIOUS") return "suspicious";
    return "dangerous";
  };

  // SVG Circumference calculation for progress ring
  const strokeDashoffset = scanResult 
    ? 2 * Math.PI * 50 * (1 - scanResult.score / 100) 
    : 0;

  return (
    <div className="app-shell">
      {/* Premium Header */}
      <header className="app-header">
        <div className="header-title-container">
          <svg className="logo-icon" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M256 80 L380 135 C380 270 315 365 256 425 C197 365 132 270 132 135 Z" 
                  fill="url(#shieldGradIcon)" stroke="#6366f1" strokeWidth="8" />
            <defs>
              <linearGradient id="shieldGradIcon" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#a855f7" />
                <stop offset="50%" stopColor="#6366f1" />
                <stop offset="100%" stopColor="#06b6d4" />
              </linearGradient>
            </defs>
          </svg>
          <h1 className="app-title">PhishGuard</h1>
        </div>
        <div>
          {isOnline ? (
            <span className="online-badge">⚡ Online Engine</span>
          ) : (
            <span className="offline-badge">📴 Offline Local</span>
          )}
        </div>
      </header>

      {/* Main Container */}
      <main className="app-main">
        
        {/* VIEW 1: URL CHECKER */}
        <section className={`tab-view ${activeTab === "check" ? "active" : ""}`}>
          <div className="checker-box glass-card">
            <h2 style={{ fontSize: "20px", fontWeight: "700" }}>Check a Website</h2>
            <p className="hero-subtitle">Type, paste, or scan a web URL to analyze risk factors.</p>
            
            <div className="input-container mt-2">
              <input
                type="text"
                placeholder="e.g. paypal-login-update.com"
                value={urlInput}
                onChange={(e) => setUrlInput(e.target.value)}
                className="url-input"
                onKeyDown={(e) => e.key === "Enter" && handleCheckUrl()}
              />
              {urlInput && (
                <button onClick={handleClearInput} className="clear-btn">
                  ✕
                </button>
              )}
            </div>

            <button 
              onClick={() => handleCheckUrl()}
              className="btn btn-primary btn-full mt-2"
              disabled={!urlInput.trim()}
            >
              🔒 Analyze Link Safety
            </button>
          </div>

          {/* Analysis Result Dashboard */}
          {scanResult && (
            <div className="glass-card mt-2">
              <div className="result-header">
                {/* Gauge Chart */}
                <div className="score-gauge-container">
                  <svg className="score-gauge">
                    <circle className="circle-bg" cx="60" cy="60" r="50" />
                    <circle 
                      className={`circle-progress ${getRatingColorClass(scanResult.rating)}`} 
                      cx="60" 
                      cy="60" 
                      r="50"
                      strokeDasharray={2 * Math.PI * 50}
                      strokeDashoffset={strokeDashoffset}
                    />
                  </svg>
                  <div className="score-text-wrapper">
                    <span className="score-num">{scanResult.score}</span>
                    <span className="score-label">Safety</span>
                  </div>
                </div>

                <div className={`rating-badge ${getRatingColorClass(scanResult.rating)}`}>
                  {scanResult.rating}
                </div>

                <p className="result-url">{scanResult.url}</p>
              </div>

              <div style={{ padding: "0 24px 24px 24px" }} className="result-details">
                {/* Warnings List */}
                {scanResult.warnings.length > 0 && (
                  <div>
                    <h3 className="detail-section-title">
                      <span>⚠️</span> Threat Factors ({scanResult.warnings.length})
                    </h3>
                    <div className="warning-list mt-2">
                      {scanResult.warnings.map((warning) => (
                        <div 
                          key={warning.id} 
                          className={`warning-item severity-${warning.severity}`}
                        >
                          <div className="warning-item-header">
                            <span className="warning-title">{warning.title}</span>
                            <span className="warning-severity">{warning.severity} Risk</span>
                          </div>
                          <p className="warning-desc">{warning.desc}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Safe Signals */}
                {scanResult.safeIndicators.length > 0 && (
                  <div className="mt-4">
                    <h3 className="detail-section-title">
                      <span className="safe-icon">✓</span> Security Controls Passed
                    </h3>
                    <div className="safe-list mt-2">
                      {scanResult.safeIndicators.map((indicator, index) => (
                        <div key={index} className="safe-item">
                          <span className="safe-icon">✓</span>
                          <span>{indicator}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Diagnostic Details Grid */}
                <div className="mt-4">
                  <h3 className="detail-section-title">
                    <span>⚙️</span> Technical Metadata
                  </h3>
                  <div className="features-grid">
                    <div className="feature-pill">
                      <span className="feature-pill-label">TLD Dots</span>
                      <span className="feature-pill-val">{scanResult.features.nb_dots}</span>
                    </div>
                    <div className="feature-pill">
                      <span className="feature-pill-label">HTTPS</span>
                      <span className={`feature-pill-val ${scanResult.features.isHttps ? 'highlight' : ''}`}>
                        {scanResult.features.isHttps ? 'Yes' : 'No'}
                      </span>
                    </div>
                    <div className="feature-pill">
                      <span className="feature-pill-label">Keywords</span>
                      <span className="feature-pill-val">{scanResult.features.sensitive_words_count}</span>
                    </div>
                    <div className="feature-pill">
                      <span className="feature-pill-label">ML Prob.</span>
                      <span className="feature-pill-val">
                        {(scanResult.mlProbability * 100).toFixed(1)}%
                      </span>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          )}
        </section>

        {/* VIEW 2: QR CODE SCANNER */}
        <section className={`tab-view ${activeTab === "qr" ? "active" : ""}`}>
          <div className="glass-card" style={{ padding: "24px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: "700", marginBottom: "8px" }}>Scan QR Code</h2>
            <p className="hero-subtitle" style={{ marginBottom: "20px" }}>
              Aim your camera at a QR code, or upload an image, to safely extract and scan its link.
            </p>
            <QrScanner 
              onScanSuccess={handleQrScanSuccess} 
              onScanError={(err) => {}} 
            />
          </div>
        </section>

        {/* VIEW 3: SCAN HISTORY */}
        <section className={`tab-view ${activeTab === "history" ? "active" : ""}`}>
          <div className="glass-card" style={{ padding: "24px" }}>
            <div className="history-header">
              <h2 className="history-title">Recent Scans</h2>
              {scanHistory.length > 0 && (
                <button onClick={handleClearHistory} className="clear-history-btn">
                  Clear All
                </button>
              )}
            </div>

            {scanHistory.length === 0 ? (
              <div className="empty-state">
                <span className="empty-icon">📂</span>
                <p>No recent scans available.</p>
                <p style={{ fontSize: "12px" }}>Your links and scanned QR codes will appear here.</p>
              </div>
            ) : (
              <div className="history-list mt-4">
                {scanHistory.map((item, index) => (
                  <div 
                    key={index} 
                    className="history-item glass-card"
                    onClick={() => {
                      setUrlInput(item.url);
                      handleCheckUrl(item.url);
                      setActiveTab("check");
                    }}
                  >
                    <div className="history-item-info">
                      <span className="history-item-url">{item.url}</span>
                      <span className="history-item-date">{item.date}</span>
                    </div>
                    <span className={`history-item-badge ${getRatingColorClass(item.rating)}`}>
                      {item.rating}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </section>

        {/* VIEW 4: EDUCATION / TIPS */}
        <section className={`tab-view ${activeTab === "tips" ? "active" : ""}`}>
          <h2 style={{ fontSize: "20px", fontWeight: "700", paddingLeft: "4px" }}>Security Guide</h2>
          
          <div>
            {phishingTips.map((tip) => (
              <div key={tip.id} className="tip-card glass-card">
                <div className="tip-header">
                  <span className="tip-num">{tip.id}</span>
                  <h3 className="tip-title">{tip.title}</h3>
                </div>
                <p className="tip-desc">{tip.desc}</p>
              </div>
            ))}
          </div>

          {/* Interactive Quiz Component */}
          <div className="quiz-card glass-card">
            <span className="quiz-tag">Test Your Skill</span>
            <h3 className="quiz-question mt-2">
              {quizQuestions[quizIndex].question}
            </h3>

            <div className="quiz-options mt-4">
              {quizQuestions[quizIndex].options.map((option, idx) => {
                let btnClass = "";
                if (quizAnswer !== null) {
                  if (idx === quizQuestions[quizIndex].correct) {
                    btnClass = "correct";
                  } else if (idx === quizAnswer) {
                    btnClass = "incorrect";
                  }
                }
                
                return (
                  <button
                    key={idx}
                    onClick={() => quizAnswer === null && handleQuizAnswer(idx)}
                    className={`quiz-option ${btnClass}`}
                    disabled={quizAnswer !== null}
                  >
                    {option}
                  </button>
                );
              })}
            </div>

            {quizAnswer !== null && (
              <div className={`quiz-feedback ${quizAnswer === quizQuestions[quizIndex].correct ? "success" : "error"}`}>
                <p>{quizQuestions[quizIndex].feedback}</p>
                <button 
                  onClick={handleNextQuiz} 
                  className="btn btn-secondary mt-2" 
                  style={{ padding: "8px 16px", fontSize: "13px", borderRadius: "10px" }}
                >
                  Next Question →
                </button>
              </div>
            )}
          </div>
        </section>

      </main>

      {/* Modern Sticky Bottom Navigation */}
      <nav className="bottom-nav">
        <button 
          onClick={() => setActiveTab("check")}
          className={`nav-item ${activeTab === "check" ? "active" : ""}`}
        >
          <div className="nav-indicator"></div>
          <div className="nav-icon-container">
            <span className="nav-icon">🔍</span>
          </div>
          <span>Check Link</span>
        </button>

        <button 
          onClick={() => setActiveTab("qr")}
          className={`nav-item ${activeTab === "qr" ? "active" : ""}`}
        >
          <div className="nav-indicator"></div>
          <div className="nav-icon-container">
            <span className="nav-icon">📷</span>
          </div>
          <span>Scan QR</span>
        </button>

        <button 
          onClick={() => setActiveTab("history")}
          className={`nav-item ${activeTab === "history" ? "active" : ""}`}
        >
          <div className="nav-indicator"></div>
          <div className="nav-icon-container">
            <span className="nav-icon">📜</span>
          </div>
          <span>History</span>
        </button>

        <button 
          onClick={() => setActiveTab("tips")}
          className={`nav-item ${activeTab === "tips" ? "active" : ""}`}
        >
          <div className="nav-indicator"></div>
          <div className="nav-icon-container">
            <span className="nav-icon">🎓</span>
          </div>
          <span>Security Tips</span>
        </button>
      </nav>
    </div>
  );
}
